# Generated by Django 4.1.3 on 2022-12-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_source', models.FloatField()),
                ('to_destination', models.FloatField()),
                ('distance', models.FloatField()),
                ('fuel_price', models.FloatField()),
                ('fuel_consumption', models.FloatField()),
                ('result', models.FloatField()),
            ],
        ),
    ]
