# Generated by Django 4.1.3 on 2022-12-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tppApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=700)),
            ],
        ),
        migrations.AlterField(
            model_name='predresults',
            name='from_source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='to_destination',
            field=models.CharField(max_length=100),
        ),
    ]
